### ISSUE TITLE
Upload weiterer Dateitypen (z.B. ZIP)

### ISSUE THREAD

**Issue by fapfa** [RRZE-Webteam/Webbaukasten-Design-FAU-2016#1]
Hallo,

ich fand leider keine passende Stelle für die Anfrage, deshalb poste ich das nun hier.
Wäre es möglich, den Upload weiterer Dateitypen über das Backend zu erlauben?

Technisch ist das sehr einfach - siehe hier: https://gist.github.com/ginocremer/9390731
`add_filter('upload_mimes', 'eigene_upload_mimes');`
`function eigene_upload_mimes( $vorhandene_mimes ){`
`$vorhandene_mimes['zip']  = 'application/zip';`
`return $vorhandene_mimes;`
`}`

In meinem Fall geht es um ein ZIP-Archiv, in dem sich eine Citavi-Zitationsrichtlinie (*.ccs) und eine PDF-Anleitung für Studierende befinden. Für *.ccs-Dateien existiert meiner Erkenntnis nach ja kein MIME-Type.

**Comment by steffigebel** [comment]
Ich sag jetzt mal ganz frech: nö!
ZB Zip-Dateien: Man muss den User schon die Möglichkeit geben, dass sie WISSEN, WAS sie da runterladen und nicht irgendeinen Order, den sie vor dem Download nicht einsehen können. Das macht man nicht ;-)

## Schönes Wochenende und viele Grüße ;-)

Steffi Gebel
Webmanagement
Regionales RechenZentrum Erlangen (RRZE)
Friedrich-Alexander-Universität Erlangen-Nürnberg
Martensstrasse 1, 91058 Erlangen, Germany
Tel. +49 9131 85-27807
stefanie.gebel@fau.demailto:stefanie.gebel@fau.de
www.rrze.fau.de

Von: fapfa <notifications@github.com<mailto:notifications@github.com>>
Antworten an: RRZE-Webteam/Webbaukasten-Design-FAU-2016 <reply@reply.github.com<mailto:reply@reply.github.com>>
Datum: Freitag, 26. Februar 2016 13:31
An: RRZE-Webteam/Webbaukasten-Design-FAU-2016 <Webbaukasten-Design-FAU-2016@noreply.github.com<mailto:Webbaukasten-Design-FAU-2016@noreply.github.com>>
Betreff: [Webbaukasten-Design-FAU-2016] Upload weiterer Dateitypen (z.B. ZIP) (#1)

Hallo,

ich fand leider keine passende Stelle für die Anfrage, deshalb poste ich das nun hier.
Wäre es möglich, den Upload weiterer Dateitypen über das Backend zu erlauben?

Technisch ist das sehr einfach - siehe hier: https://gist.github.com/ginocremer/9390731
add_filter('upload_mimes', 'eigene_upload_mimes');
function eigene_upload_mimes( $vorhandene_mimes ){
$vorhandene_mimes['zip'] = 'application/zip';
return $vorhandene_mimes;
}

In meinem Fall geht es um ein ZIP-Archiv, in dem sich eine Citavi-Zitationsrichtlinie (*.ccs) und eine PDF-Anleitung für Studierende befinden. Für *.ccs-Dateien existiert meiner Erkenntnis nach ja kein MIME-Type.

**Comment by cassandre** [comment]
Dies ist nur das Repository des FAU-Designs für den Webbaukasten/NavEditor. Feature-Requests für die WP-Themes bitte im entsprechenden Repository (z.B. https://github.com/RRZE-Webteam/FAU-Einrichtungen oder das der jeweiligen Fakultät) posten.
