### ISSUE TITLE
Listenformatierung im Text-Widget

### ISSUE THREAD

**Issue by pdees** [RRZE-Webteam/Webbaukasten-Design-FAU-2016#2]
Das Text-Widget setzt Überschriften und Absätze in einer kleineren Schriftgröße als in der normalen Textausgabe, was ich auch richtig finde. Aufzählungen werden aber in normaler Schriftgröße gesetzt, das müsste angepasst werden (siehe z.B. hier: https://economics-en.cms.rrze.uni-erlangen.de/)

**Comment by steffigebel** [comment]
## Das hat aber it Webbaukasten nichts zu tun!

Steffi Gebel
Webmanagement
Regionales RechenZentrum Erlangen (RRZE)
Friedrich-Alexander-Universität Erlangen-Nürnberg
Martensstrasse 1, 91058 Erlangen, Germany
Tel. +49 9131 85-27807
stefanie.gebel@fau.demailto:stefanie.gebel@fau.de
www.rrze.fau.de

Von: pdees <notifications@github.com<mailto:notifications@github.com>>
Antworten an: RRZE-Webteam/Webbaukasten-Design-FAU-2016 <reply@reply.github.com<mailto:reply@reply.github.com>>
Datum: Donnerstag, 17. März 2016 14:50
An: RRZE-Webteam/Webbaukasten-Design-FAU-2016 <Webbaukasten-Design-FAU-2016@noreply.github.com<mailto:Webbaukasten-Design-FAU-2016@noreply.github.com>>
Betreff: [Webbaukasten-Design-FAU-2016] Listenformatierung im Text-Widget (#2)

Das Text-Widget setzt Überschriften und Absätze in einer kleineren Schriftgröße als in der normalen Textausgabe, was ich auch richtig finde. Aufzählungen werden aber in normaler Schriftgröße gesetzt, das müsste angepasst werden (siehe z.B. hier: https://economics-en.cms.rrze.uni-erlangen.de/)
