### ISSUE TITLE
Sprachversion

### ISSUE THREAD

**Issue by pdees** [RRZE-Webteam/Webbaukasten-Design-FAU-2016#3]
Die Sprachversion funktioniert nur mit "English (United States)", nicht mit "English (UK)". Zumindest wird "Category" bei letzterer als "Kategorie" ausgegeben. Da gibt es Konflikte, weil das CRIS-Plugin nur mit "English (UK)" funktioniert (FAU-Person wiederum allerdings nur mit "English (US)"). Die Sprachversion sollte zumindest für alle vereinheitlicht werden, optimal gäbe es natürlich beide.

**Comment by steffigebel** [comment]
## Das hier betrifft auch nicht den Webbaukasten, denke ich.

Steffi Gebel
Webmanagement
Regionales RechenZentrum Erlangen (RRZE)
Friedrich-Alexander-Universität Erlangen-Nürnberg
Martensstrasse 1, 91058 Erlangen, Germany
Tel. +49 9131 85-27807
stefanie.gebel@fau.demailto:stefanie.gebel@fau.de
www.rrze.fau.de

Von: pdees <notifications@github.com<mailto:notifications@github.com>>
Antworten an: RRZE-Webteam/Webbaukasten-Design-FAU-2016 <reply@reply.github.com<mailto:reply@reply.github.com>>
Datum: Donnerstag, 17. März 2016 14:52
An: RRZE-Webteam/Webbaukasten-Design-FAU-2016 <Webbaukasten-Design-FAU-2016@noreply.github.com<mailto:Webbaukasten-Design-FAU-2016@noreply.github.com>>
Betreff: [Webbaukasten-Design-FAU-2016] Sprachversion (#3)

Die Sprachversion funktioniert nur mit "English (United States)", nicht mit "English (UK)". Zumindest wird "Category" bei letzterer als "Kategorie" ausgegeben. Da gibt es Konflikte, weil das CRIS-Plugin nur mit "English (UK)" funktioniert (FAU-Person wiederum allerdings nur mit "English (US)"). Die Sprachversion sollte zumindest für alle vereinheitlicht werden, optimal gäbe es natürlich beide.
